maxconn = 32
httpchk = "GET /"

[defaults]
timeout_connect = "5000ms"
timeout_client = "50000ms"
timeout_server = "50000ms"

[[default_options]]
option = "tcplog"

[[default_options]]
option = "redispatch"

[backend]
balance = "leastconn"
timeout_client = "50000ms"
timeout_server = "50000ms"
option = "clitcpka"
checks = "check inter 5s rise 2 fall 3"

[front-end]
listen = "*"
port = 8000
mode = "http"

[status]
enabled = true
listen = "*"
port = 9000
user = "admin"
password = "password"
uri = "/haproxy-stats"

[[server]]
name = "primeiro"
host_or_ip = "127.0.0.1"
port = "8080"

[[server]]
name = "second"
host_or_ip = "127.0.0.1"
port = "8181"

# optional
[[listen_server]]
name = "management"
port = "8989"
listen = "*"
mode = "http"
balance = "roundrobin"
httpchk = "GET /"
